//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkadhiaSoulsHunters.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cazador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cazador()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int nivel { get; set; }
        public int almas { get; set; }
        public int salud { get; set; }
        public int estamina { get; set; }
        public int supervivencia { get; set; }
        public int fuerza { get; set; }
        public int detreza { get; set; }
        public int poder { get; set; }
        public int resistenciaFisica { get; set; }
        public int resistenciaTierra { get; set; }
        public int resistenciaAgua { get; set; }
        public int resistenciaHielo { get; set; }
        public int resistenciaAire { get; set; }
        public int resistenciaFuego { get; set; }
        public int resistenciaOscuridad { get; set; }
        public int resistenciaLuz { get; set; }
        public int equipoActivo { get; set; }
    
        public virtual Equipacion Equipacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
