//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkadhiaSoulsHunters.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criatura
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public float ataqueFisico { get; set; }
        public int ataqueTierra { get; set; }
        public int ataqueAgua { get; set; }
        public int ataqueHielo { get; set; }
        public int ataqueAire { get; set; }
        public int ataqueFuego { get; set; }
        public int ataqueOscuridad { get; set; }
        public int ataqueLuz { get; set; }
        public int poder { get; set; }
        public int resistenciaFisica { get; set; }
        public int resistenciaTierra { get; set; }
        public int resistenciaAgua { get; set; }
        public int resistenciaHielo { get; set; }
        public int resistenciaAire { get; set; }
        public int resistenciaFuego { get; set; }
        public int resistenciaOscuridad { get; set; }
        public int resistenciaLuz { get; set; }
        public int tipoCriatura { get; set; }
    
        public virtual TipoCriatura TipoCriatura1 { get; set; }
    }
}
