//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkadhiaSoulsHunters.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipacion()
        {
            this.Cazador = new HashSet<Cazador>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int casco { get; set; }
        public int peto { get; set; }
        public int brazales { get; set; }
        public int cinto { get; set; }
        public int grebas { get; set; }
        public int arma { get; set; }
    
        public virtual Arma Arma1 { get; set; }
        public virtual Brazales Brazales1 { get; set; }
        public virtual Casco Casco1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cazador> Cazador { get; set; }
        public virtual Cinto Cinto1 { get; set; }
        public virtual Peto Peto1 { get; set; }
        public virtual Grebas Grebas1 { get; set; }
    }
}
