//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkadhiaSoulsHunters.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arkadhiashdbEntities : DbContext
    {
        public arkadhiashdbEntities()
            : base("name=arkadhiashdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arma> Arma { get; set; }
        public virtual DbSet<Brazales> Brazales { get; set; }
        public virtual DbSet<Casco> Casco { get; set; }
        public virtual DbSet<Cazador> Cazador { get; set; }
        public virtual DbSet<Cinto> Cinto { get; set; }
        public virtual DbSet<Criatura> Criatura { get; set; }
        public virtual DbSet<Equipacion> Equipacion { get; set; }
        public virtual DbSet<Grebas> Grebas { get; set; }
        public virtual DbSet<Lugar> Lugar { get; set; }
        public virtual DbSet<Objeto> Objeto { get; set; }
        public virtual DbSet<Peto> Peto { get; set; }
        public virtual DbSet<TipoCriatura> TipoCriatura { get; set; }
        public virtual DbSet<TipoObjeto> TipoObjeto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
